# Generated by Django 5.0.6 on 2024-07-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='telegram_id',
        ),
    ]
